### ISSUE TITLE
[FEATURE] UsernameFile && PasswordFile option

### ISSUE THREAD

**Issue by anotherhadi** [Fuwn/pia.nix#1]
Add an option to get the username & password from a file to allow users to add sops generated paths.

**Comment by Fuwn** [comment]
Thanks for the suggestion. Done.

Does https://github.com/Fuwn/pia.nix/commit/00b32ae13529e74348192e018b9b7962096e74ea work for you?

**Comment by anotherhadi** [comment]
> Does [00b32ae](https://github.com/Fuwn/pia.nix/commit/00b32ae13529e74348192e018b9b7962096e74ea) work for you?

It seems to work, however I have the error "/run/current-system/sw/bin/pia: line 6: exec: doas: not found"

**Comment by Fuwn** [comment]
https://github.com/Fuwn/pia.nix/commit/445e82bd030080fb250f83805a7cc2feeea174c9 *should* fix that by correctly falling back on Sudo.

**Comment by anotherhadi** [comment]
Yes perfect! :) Ty a lot
